### ISSUE TITLE
Unexpected divide by zero

### ISSUE THREAD

**Issue by neitzke** [chan-y-park/loom#18]
With the current master, choosing differentials

```
{4: 9*z^2, 3: 4, 2: - 10*z}
```

I get the error

```
23954: Getting aligned x's at the base point z = (-6.0611049247490908971e-9 - 1.1388728074616771985j).
23954: Analyzing a branch point at z = (0.33367444189398689285 + 0.089407797240399354414j).
23954: Analyzing a branch point at z = (-0.24426664109717826733 + 0.24426664109717822897j).
23954: Analyzing a branch point at z = (-0.6351237842637036409 - 0.17018090508725803687j).
23954: Analyzing a branch point at z = (0.17018090508725793715 + 0.63512378426370366762j).
23954: Analyzing a branch point at z = (0.46494283925340683174 - 0.46494283925340675874j).
23954: Analyzing a branch point at z = (-0.089407797240399302024 - 0.33367444189398690689j).
23954: start cpu time: 1442779826.52
23954: Generate a single spectral network at theta = 1.0.
23954: Start growing a new spectral network...
23954: Seed S-walls at branch points...
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1535, in __call__
    return self.func(*args)
  File "/home/andy/loom/loom/gui.py", line 262, in button_generate_action
    phase=eval(self.entry_phase.get()),
  File "/home/andy/loom/loom/api.py", line 78, in generate_spectral_network
    spectral_network.grow(config, sw)
  File "/home/andy/loom/loom/spectral_network.py", line 51, in grow
    bp, config)
  File "/home/andy/loom/loom/s_wall.py", line 641, in get_s_wall_seeds
    omega_1 = exp(2*pi*1j/rp.i)
ZeroDivisionError: complex division by zero
```

**Comment by plonghi** [comment]
Hi Andy,

that is a problem with ramification points apparently, the division by zero happens because some of the m_x (ramification indices) are zero.
A quick workaround that Chan suggested, and worked for me in another example, was to increase the 'accuracy' parameter, i.e. from 10^-6 to 10^-4 for example.

I guess this issue goes classified under the precision of ramification points perhaps?
